### ISSUE TITLE
tt daemon

### ISSUE THREAD

**Issue by unera** [tarantool/tt#10]
The module is used to start (not use) supervisor daemon.

- `tt tvisord [supervisors options]`

Config options: 

```yaml
# tarantool.yaml
tvisord:
   port: 3201   # default value
   tls:  # optional
      cert: path/to
      key: path/to
   pid: path/to/tvisord.pid
   log:
      type: file # disabled, syslog
      dir: path/to/logdir
```

Options:

- `--port` - listen port
- `--tls{-cert,-key}` - TLS options

How to work:

1. It runs HTTP[S] server that listens `tvisord.port`
2. Provide easy protocol

Request:

```http
POST /tt/etc/tarantool HTTP/1.0
Content-Type: application/json

{
    "module": "version",
    "root": "/etc/tarantool",
    "args": [],
    "opts": { "short": true }
}
```

Response:

```http
200 Ok
Content-Type: application/json

{
   "status": "ok",
   "version": "2.3.4.5"
}
```

3. The server runs `tt module` (using `ENV=TVISORD=yaml`). Parse its output and response.

### Authorisation and authentication

TODO: To auth, the server uses `tt tvisorauth`
Update: see #23
