### ISSUE TITLE
aeon: connect by a credentials found in a config

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/tt#1051]
Aeon exports an URI and params to connect into the `aeon.grpc` role as an `advertise` URI (not `listen`):
```
instances:
  aeon-grpc-router-001:
    roles_cfg:
      aeon.grpc:
        listen:
          uri: 'http://localhost:50051/'
          params:
            transport: 'ssl'
            ssl_key_file: './ssl_cert/server.key'
            ssl_cert_file: './ssl_cert/server.crt'
        advertise:
          uri: 'http://localhost:50051/'
          params:
            transport: 'ssl'
```

The command:

```
tt aeon connect -c config instance
```

Should be able to connect to an instance described in the cluster config.

See and its usage inside tt to load/parse a config file:
https://github.com/tarantool/tt/tree/master/lib/cluster
