### ISSUE TITLE
Bring order to the directory tree

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/tt#109]
Implementing new functionality, we regularly encounter the lack of a fixed directory system in `tt`.
Issues to be solved (in code and docs) as part of this task:
- default values in case the values are missing in `tarantool.yaml`
- values in the system `tarantool.yaml`
- using relative paths in `tarantool.yaml`
- paths where the instance artifact is stored (`log`, `xlog`, `nap`, `PIDfiles`...)
- paths where the `modules`, `rocks`, ... stored
- maybe something else

**Comment by 0x501D** [comment]
Assume we have this app tree:

```
.
├── a.lua
├── b
│   └── init.lua
├── demo
│   ├── init.lua
│   ├── instances.yml
│   └── router.init.lua
└── tarantool.yaml

```
tarantool.yaml:

```yaml
tt:
  app:
    instances_available: "/home/void/stuff/tt-app/app"
    run_dir: "run"
    data_dir: "data"
    log_dir: "log"
```
demo/instances.yml: 
```yaml
router:
master:
replica:
```
tree after `tt srart a`:
```
.
├── a.lua
├── b
│   └── init.lua
├── data
│   └── a
├── demo
│   ├── init.lua
│   ├── instances.yml
│   └── router.init.lua
├── log
│   └── a
│       └── a.log
├── run
│   └── a
│       ├── a.control
│       └── a.pid
└── tarantool.yaml
```
`tt srart b`

```
.
├── a.lua
├── b
│   └── init.lua
├── data
│   ├── a
│   └── b
├── demo
│   ├── init.lua
│   ├── instances.yml
│   └── router.init.lua
├── log
│   ├── a
│   │   └── a.log
│   └── b
│       └── b.log
├── run
│   ├── a
│   │   ├── a.control
│   │   └── a.pid
│   └── b
│       ├── b.control
│       └── b.pid
└── tarantool.yaml
```

`tt srart demo`
```
.
├── a.lua
├── b
│   └── init.lua
├── data
│   ├── a
│   ├── b
│   └── demo
│       ├── master
│       ├── replica
│       └── router
├── demo
│   ├── init.lua
│   ├── instances.yml
│   └── router.init.lua
├── log
│   ├── a
│   │   └── a.log
│   ├── b
│   │   └── b.log
│   └── demo
│       ├── master
│       │   └── master.log
│       ├── replica
│       │   └── replica.log
│       └── router
│           └── router.log
├── run
│   ├── a
│   │   ├── a.control
│   │   └── a.pid
│   ├── b
│   │   ├── b.control
│   │   └── b.pid
│   └── demo
│       ├── master
│       │   ├── master.control
│       │   └── master.pid
│       ├── replica
│       │   ├── replica.control
│       │   └── replica.pid
│       └── router
│           ├── router.control
│           └── router.pid
└── tarantool.yaml
```

**Comment by vr009** [comment]
I had a plan to pack and distribute applications (see [tt pack](https://github.com/tarantool/tt/issues/18#issuecomment-1200126905)) like this way:

```
temp
├── a.lua
├── env
│   ├── bin
│   │   ├── tarantool
│   │   └── tt
│   └── modules
│       └── module1
├── tarantool.yaml
└── var
    ├── data
    ├── lib
    ├── log
    └── pid
```

`tarantool.yaml` would be the next:

```yaml
tt:
  modules:
    directory: env/modules
  app:
    instances_available: .
    run_dir: var
    log_dir: var/log
    log_maxsize: 1
    log_maxage: 1
    log_maxbackups: 1
    restart_on_failure: true
    data_dir: data
    bin_dir: env/bin
```
