### ISSUE TITLE
Add basic option `--yaml` (integration with tvisor)

### ISSUE THREAD

**Issue by unera** [tarantool/tt#22]
Add the basic option (`--yaml`) for tvisor.

Output format for each module:

```yaml
tt:
   status: ok  # or error
   http:  200 # optional. default 200 for 0, 500 for not 0 exit code

   # the other results
```
example:

```
tt version --yaml
tt:
   status: ok
   version: 2.8.1
```

PS: Also the option can be set by ENV variable `TVISORD=yaml[,theotheroptions]`

if `split(/\s*,\s*/, $ENV{TVISORD})` contains `yaml`, then the option have to be set on.
