### ISSUE TITLE
Different dir names for artifacts in with/without `tt init` usage cases

### ISSUE THREAD

**Issue by AnaNek** [tarantool/tt#223]
When we use `tt init` we get `tarantool.yaml` with this content:

```yaml
tt:
  modules:
    directory: modules
  app:
    run_dir: var/run
    log_dir: var/log
    log_maxsize: 100
    log_maxage: 8
    log_maxbackups: 10
    restart_on_failure: false
    data_dir: var/lib
    bin_dir: bin
    inc_dir: include
    instances_enabled: instances.enabled
...
```

So default directories for artifacts are in `var` directory.

      └── var
          ├── lib
          ├── log
          └── run

But when we create `tarantool.yaml` file manually with empty
`run_dir`, `log_dir`, `data_dir` for app and assume that default
values will be used:

```yaml
tt:
  app:
    instances_enabled: .
```

we start application and artifacts are written in `run`, `log`, `data` dirs.

          ├── data
          ├── log
          └── run

And we don't have such structure as we have when we use `tt init`.
