### ISSUE TITLE
tt pack: support separate wal, vinyl, snap directories

### ISSUE THREAD

**Issue by psergee** [tarantool/tt#328]
`tt pack` need to be updated to support packing of the environment with different data directories. For example, if `tt.yaml` has the following configuration:
```yaml
    tt:                                                                                                                                                    
      app:
        instances_enabled: path/to/available/applications
        wal_dir: var/wal                                                                   
        vinyl_dir: var/vinyl
        memtx_dir: var/snap
```
`tt pack` must pack wal, vinyl and snapshot artifacts to different target directories, because they are different in user environment.
The same paths must be copied to default data dir - var/lib
