### ISSUE TITLE
Add support for templates in tt config.

### ISSUE THREAD

**Issue by psergee** [tarantool/tt#617]
To support more flexible environment configuration and convenient tarantool 3.0 integration, it would be nice to support templates in tt config file. Examples, local:
``` yaml
tt:
  app:
    run_dir: "var/run/{{ instance_name }}"
    log_dir: "var/log/{{ instance_name }}"
    wal_dir: "var/lib/{{ instance_name }}"
    memtx_dir: "var/lib/{{ instance_name }}"
    vinyl_dir: "var/lib/{{ instance_name }}"
```
Pid file location will be `<instances_enabled>/app/var/run/master/tarantool.control`
Global (absolute paths):
``` yaml
tt:
  app:
    run_dir: "/var/run/tarantool/{{ app_name}}/{{ instance_name }}"
    log_dir: "/var/log/tarantool{{ app_name}}/{{ instance_name }}"
    wal_dir: "/var/lib/tarantool/{{ app_name}}/{{ instance_name }}"
    memtx_dir: "/var/lib/tarantool/{{ app_name}}/{{ instance_name }}"
    vinyl_dir: "/var/lib/tarantool/{{ app_name}}/{{ instance_name }}"
```
Pid file location will be "/var/run/tarantool/app/master/tarantool.control"
After adding the templates support, all the logic for appending app/instance name suffixes to paths must be removed.
Tarantoolctl layout can be represented by the following paths:
``` yaml
tt:
  app:
    run_dir: "var/run/"
    log_dir: "var/log/"
    wal_dir: "var/lib/{{ instance_name }}"
    memtx_dir: "var/lib/{{ instance_name }}"
    vinyl_dir: "var/lib/{{ instance_name }}"
```

`cartridge` sub-command code must be updated to support instances navigation with updated layout. Currently it accepts a run dir path and makes an assumption about the file tree structure in this directory. `tt cartridge` sub-commands must be able to work with any layout specified by a user in `tt.yaml` config.
