### ISSUE TITLE
[tt] misinterprets the relative path to the templates folder

### ISSUE THREAD

**Issue by dkasimovskiy** [tarantool/tt#671]
Steps to reproduce:
1. Init tt in the folder inside your home directory (`cd /home/d/git && tt init`)
2. Set relative path to the templates folder in the _/home/d/git/tt.yaml_ (`~/git/repo/templates/tt`)
3. Try to create new app with template (`tt create tdg --name tt_tdg_app`)
4. Got error ` template 'tdg' is not found`

```
d@m1book8715:~/git$ tt cfg dump
/home/d/git/tt.yaml:
tt:
  modules:
    directory: /home/d/git/modules
  app:
    run_dir: /home/d/git/var/run
    log_dir: /home/d/git/var/log
    log_maxsize: 100
    log_maxage: 8
    log_maxbackups: 10
    restart_on_failure: false
    wal_dir: /home/d/git/var/lib
    memtx_dir: /home/d/git/var/lib
    vinyl_dir: /home/d/git/var/lib
    bin_dir: /home/d/git/bin
    inc_dir: /home/d/git/include
    instances_enabled: /home/d/git/instances.enabled
    tarantoolctl_layout: false
  ee:
    credential_path: ""
  templates:
  - path: /home/d/git/~/git/repo/templates/tt
  repo:
    rocks: ""
    distfiles: /home/d/git/distfiles
```

Expected behavior:
 - Relative paths works correctly
