### ISSUE TITLE
Provide the '--sslpassword' command-line parameter for 'tt connect'

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/tt#734]
Consider the following Tarantool configuration:

```
iproto:
  listen:
  - uri: '127.0.0.1:3301'
    params:
      transport: 'ssl'
      ssl_ca_file: 'test_certs/ca.crt'
      ssl_cert_file: 'test_certs/localhost.crt'
      ssl_key_file: 'test_certs/localhost.key'
      ssl_password: 'qwerty'
```

[Full GitHub example](https://github.com/tarantool/doc/blob/3.0-iproto-uri-params/doc/code_snippets/snippets/config/instances.enabled/ssl/config.yaml)

Connecting to such instance requires the `--sslpassword` command-line option for the `tt connect` command.

<img width="1417" alt="image" src="https://github.com/tarantool/tt/assets/38073144/e3764190-0e56-4907-a523-d5d15d3c938f">
