### ISSUE TITLE
start: failed to start Tarantool 3 with encrypted etcd

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tt#938]
Config file:
```yaml
config:
  etcd:
    endpoints:
    - https://localhost:2379
    ssl:
      verify_peer: false
      ca_file: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert/ca.crt
      ssl_key: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert/localhost.key
      ca_path: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert
      verify_host: false
      ssl_cert: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert/localhost.crt
    prefix: /cluster_a/
```

```bash
tt start test_app
```
```
   ⨯ can't collect instance information for test_app: error loading instance "cluster_a-storage-2-2" configuration from config "/home/moiseevgeorgy/Development/github/tarantool/cluster-federation/instances.enabled/test_app/config.yaml": unable to connect to etcd: fail to create tls client config: KeyFile and CertFile must both be present[key: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert/localhost.key, cert: ]
```
